### PR TITLE
Let data writer distinguish between m and g as product dimensions

### PR DESCRIPTION
**Pull request by Merjo**

### CODE REVIEW

**Review by JakobBD — APPROVED** [review]
I'm going to blindly approve this. The function urgently needs refactoring, which will remove the need for this. I don't object to having whatever in the meantime.

**Comment by Merjo** [comment]
Thank you - I was thinking as well that a refactoring would be good, right now the sankey diagram just shows the results for the CAZ region in 2050, and it would be good if this could be parameterized in the config or something, ideally with also the option to sum over the regions to get a total world figure. I'm prioritizing other things right now but could propose an implementation if needed as well.

**Comment by Merjo** [comment]
What is our protocol on merging pull requests after one person has approved them? Can I just go ahead or should we wait for everybody to approve? Just new to Git :)

**Comment by JakobBD** [comment]
I've added a git page on this, to have a common understanding: https://github.com/pik-piam/sodym/wiki/Git-protocol
Feel free to make/propose changes, but inform the others (e.g. on mattermost)

**Pull request merged**
