### PR TITLE
Flexible datainput

### PR DESCRIPTION
**Pull request by JakobBD**

### CODE REVIEW

**Comment by JakobBD** [comment]
Still needs tests, testing, adapted examples.

**Comment by SallyDa** [comment]
Can we keep the current very flexible DataReader as is please? And then make this one a child class with an init that takes the DimensionReader and ParameterReader, and read_parameters that then calls self.parameter_reader.read_all? This way you also won't need to update the examples.

**Comment by JakobBD** [comment]
Ah yes, that should work, nice suggestion. I will try it out. 
I was going to ask you if you found a way that was closer to your current implementation, with no compromise on API. This actually seems to achieve it. 

There's a few other things I'm going to ask your opinion/input on once I have a working version.

**Comment by SallyDa** [comment]
Perfect, let me know when you have finished/tested :)

**Pull request merged**
