### PR TITLE
Stop git tracking poetry.lock

### PR DESCRIPTION
**Pull request by SallyDa**
As discussed, we don't need to track this file, as
* it can be generated from the pyproject.toml
* sodym is a library, and should be a little bit flexible on versions of its dependencies (as specified in the pyproject.toml) to be compatible with other applications

### CODE REVIEW

**Comment by JakobBD** [comment]
Look good. Maybe we should add it to `.gitignore` as well?

**Comment by JakobBD** [comment]
@Merjo merging this PR will delete your poetry.lock. So before doing so, consider copying the poetry.lock to a different directory, and moving it back afterwards.

**Comment by SallyDa** [comment]
I think it should also work that you don't lose your local poetry.lock if you run "git rm --cached poetry.lock" before merging.

**Comment by Merjo** [comment]
Thank you both, it worked for now.

**Pull request merged**
