### PR TITLE
Small changes to DimensionSet

### PR DESCRIPTION
**Pull request by JakobBD**
move dimension set union and intersection to DimensionSet object; rename dimensions to dim_list

### CODE REVIEW

**Comment by JakobBD** [comment]
Will adapt simson, but not the notebooks before #33 is merged. I propose this order: 
- merge #33 into develop (needs your review)
- merge develop here 
- adapt notebooks 

Okay?

**Comment by JakobBD** [comment]
Update: Simson does not appear to need updates. 
(I actually checked that when I did the PR)

**Comment by SallyDa** [comment]
In general I am not a fan of merging stuff that breaks other functionality, but since you are working on the notebooks separately, then yes, we can do this.

**Review by SallyDa — APPROVED** [review]

**Comment by JakobBD** [comment]
Ah no, I meant to do this all before merging this PR :-)

**Comment by JakobBD** [comment]
adapted notebooks, fixed merge bugs

**Pull request merged**
